# ======== GENERAL ========
server:
  port: 8084

userApi:
  path: http://localhost:8085/api/user

# ======== JWT ========
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  prefix: "Bearer "

# ======== H2 ========
spring:
  h2:
    console:
      enabled: true